### ISSUE TITLE
how can i add multiple bots within the same NestJs App

### ISSUE THREAD

**Issue by iafine** [necordjs/necord#750]
### What is your question?

I have three channels within different self-bot, and I want to listen multiple bot messages in a NestApp. 

How can i add multiple bots within the same NestJs App?

Thanks for your help!

**Comment by SocketSomeone** [comment]
@iafine Thank you for your question! Multiple bots not supported due to the technical capabilities of @nestjs

You can import all your bot modules to app module

AppModule
├── FirstBotModule (With NecordModule.forRoot)
└── SecondBotModule (With another NecordModule.forRoot)

But Necord using global module for explore all providers with commands.
For this reason, usage of multiple bots may to be hard. (Injecting client provider and other services overlaps)


Also, don't forget about ratelimits by ip, usage multiple popular bots can have restrictions

If you know solution how to support it better feel free to create a PR
